/*******************************************************************************
 * Qantiqa : Decentralized microblogging platform
 * Copyright (C) 2010 Dario (i@dario.im) 
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 ******************************************************************************/

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error.proto

package proto;

public final class Error {
    private Error() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public static final class hash extends com.google.protobuf.GeneratedMessage {
        // Use hash.newBuilder() to construct.
        private hash() {
            initFields();
        }

        private hash(boolean noInit) {
        }

        private static final hash defaultInstance;

        public static hash getDefaultInstance() {
            return defaultInstance;
        }

        public hash getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return proto.Error.internal_static_hash_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return proto.Error.internal_static_hash_fieldAccessorTable;
        }

        // optional string error = 1;
        public static final int ERROR_FIELD_NUMBER = 1;
        private boolean hasError;
        private java.lang.String error_ = "";

        public boolean hasError() {
            return hasError;
        }

        public java.lang.String getError() {
            return error_;
        }

        // optional string request = 2;
        public static final int REQUEST_FIELD_NUMBER = 2;
        private boolean hasRequest;
        private java.lang.String request_ = "";

        public boolean hasRequest() {
            return hasRequest;
        }

        public java.lang.String getRequest() {
            return request_;
        }

        private void initFields() {
        }

        public final boolean isInitialized() {
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (hasError()) {
                output.writeString(1, getError());
            }
            if (hasRequest()) {
                output.writeString(2, getRequest());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (hasError()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeStringSize(1, getError());
            }
            if (hasRequest()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeStringSize(2, getRequest());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        public static proto.Error.hash parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static proto.Error.hash parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static proto.Error.hash parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static proto.Error.hash parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static proto.Error.hash parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static proto.Error.hash parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static proto.Error.hash parseDelimitedFrom(
                java.io.InputStream input) throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static proto.Error.hash parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static proto.Error.hash parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static proto.Error.hash parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(proto.Error.hash prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> {
            private proto.Error.hash result;

            // Construct using proto.Error.hash.newBuilder()
            private Builder() {
            }

            private static Builder create() {
                Builder builder = new Builder();
                builder.result = new proto.Error.hash();
                return builder;
            }

            protected proto.Error.hash internalGetResult() {
                return result;
            }

            public Builder clear() {
                if (result == null) {
                    throw new IllegalStateException(
                            "Cannot call clear() after build().");
                }
                result = new proto.Error.hash();
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(result);
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return proto.Error.hash.getDescriptor();
            }

            public proto.Error.hash getDefaultInstanceForType() {
                return proto.Error.hash.getDefaultInstance();
            }

            public boolean isInitialized() {
                return result.isInitialized();
            }

            public proto.Error.hash build() {
                if (result != null && !isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return buildPartial();
            }

            private proto.Error.hash buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                if (!isInitialized()) {
                    throw newUninitializedMessageException(result)
                            .asInvalidProtocolBufferException();
                }
                return buildPartial();
            }

            public proto.Error.hash buildPartial() {
                if (result == null) {
                    throw new IllegalStateException(
                            "build() has already been called on this Builder.");
                }
                proto.Error.hash returnMe = result;
                result = null;
                return returnMe;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof proto.Error.hash) {
                    return mergeFrom((proto.Error.hash) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(proto.Error.hash other) {
                if (other == proto.Error.hash.getDefaultInstance())
                    return this;
                if (other.hasError()) {
                    setError(other.getError());
                }
                if (other.hasRequest()) {
                    setRequest(other.getRequest());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                        .newBuilder(this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                    case 0:
                        this.setUnknownFields(unknownFields.build());
                        return this;
                    default: {
                        if (!parseUnknownField(input, unknownFields,
                                extensionRegistry, tag)) {
                            this.setUnknownFields(unknownFields.build());
                            return this;
                        }
                        break;
                    }
                    case 10: {
                        setError(input.readString());
                        break;
                    }
                    case 18: {
                        setRequest(input.readString());
                        break;
                    }
                    }
                }
            }

            // optional string error = 1;
            public boolean hasError() {
                return result.hasError();
            }

            public java.lang.String getError() {
                return result.getError();
            }

            public Builder setError(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                result.hasError = true;
                result.error_ = value;
                return this;
            }

            public Builder clearError() {
                result.hasError = false;
                result.error_ = getDefaultInstance().getError();
                return this;
            }

            // optional string request = 2;
            public boolean hasRequest() {
                return result.hasRequest();
            }

            public java.lang.String getRequest() {
                return result.getRequest();
            }

            public Builder setRequest(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                result.hasRequest = true;
                result.request_ = value;
                return this;
            }

            public Builder clearRequest() {
                result.hasRequest = false;
                result.request_ = getDefaultInstance().getRequest();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:hash)
        }

        static {
            defaultInstance = new hash(true);
            proto.Error.internalForceInit();
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:hash)
    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_hash_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_hash_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\013error.proto\"&\n\004hash\022\r\n\005error\030\001 \001(\t\022\017\n\007"
                + "request\030\002 \001(\tB\007\n\005proto" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_hash_descriptor = getDescriptor()
                        .getMessageTypes().get(0);
                internal_static_hash_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_hash_descriptor,
                        new java.lang.String[] { "Error", "Request", },
                        proto.Error.hash.class, proto.Error.hash.Builder.class);
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(
                        descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {},
                        assigner);
    }

    public static void internalForceInit() {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
